//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentasPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO_ROL
    {
        public int id_user_rol { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_rol { get; set; }
    
        public virtual TB_ROL TB_ROL { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
    }
}
